# Generated by Django 5.0.6 on 2024-08-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_date_dailytask_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
