# Generated by Django 5.0.6 on 2024-08-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_dailytask_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
